import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const game=document.getElementById('game');
const rankEl=document.getElementById('rank');
const progressEl=document.getElementById('progress');
const speedEl=document.querySelector('#speed b');
const itemBtn=document.getElementById('item');
const msgEl=document.getElementById('message');
const menu=document.getElementById('menu');
const playBtn=document.getElementById('play');
const loadingEl=document.getElementById('loading');

const scene=new THREE.Scene();
scene.background=new THREE.Color(0x78b8e8);
scene.fog=new THREE.FogExp2(0x9cc7e4,.0085);

const camera=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.1,550);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));
renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.08;
game.appendChild(renderer.domElement);

scene.add(new THREE.HemisphereLight(0xd9eeff,0x50633c,2.5));
const sun=new THREE.DirectionalLight(0xfff1d4,4.1);
sun.position.set(-45,70,25);sun.castShadow=true;
sun.shadow.mapSize.set(2048,2048);
sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;
scene.add(sun);

const loader=new GLTFLoader();
const CAR_BASE='https://raw.githubusercontent.com/Arslan12216775/kenney_car-kit/master/Models/GLB%20format/';
const CAR_URLS=[CAR_BASE+'race.glb',CAR_BASE+'race-future.glb',CAR_BASE+'sedan-sports.glb',CAR_BASE+'hatchback-sports.glb',CAR_BASE+'suv-luxury.glb',CAR_BASE+'sedan.glb'];
const loadGLB=url=>new Promise((resolve,reject)=>loader.load(url,g=>resolve(g.scene),undefined,reject));

const world=new THREE.Group();scene.add(world);
const points=[new THREE.Vector3(0,0,0),new THREE.Vector3(0,0,-65),new THREE.Vector3(-20,2,-125),new THREE.Vector3(-48,4,-180),new THREE.Vector3(-25,7,-245),new THREE.Vector3(22,5,-300),new THREE.Vector3(54,2,-365),new THREE.Vector3(38,0,-430),new THREE.Vector3(-10,1,-495),new THREE.Vector3(-45,3,-555),new THREE.Vector3(-18,5,-625),new THREE.Vector3(27,2,-690),new THREE.Vector3(0,0,-770)];
const curve=new THREE.CatmullRomCurve3(points,false,'catmullrom',.35);
function basisAt(t){t=THREE.MathUtils.clamp(t,0,1);const p=curve.getPointAt(t),tangent=curve.getTangentAt(t).normalize(),up=new THREE.Vector3(0,1,0),right=new THREE.Vector3().crossVectors(tangent,up).normalize(),normal=new THREE.Vector3().crossVectors(right,tangent).normalize();return{p,tangent,right,normal}}
function buildRibbon(width,color,yOffset=0){const segs=320,pos=[],idx=[];for(let i=0;i<=segs;i++){const b=basisAt(i/segs),c=b.p.clone().addScaledVector(b.normal,yOffset),l=c.clone().addScaledVector(b.right,-width/2),r=c.clone().addScaledVector(b.right,width/2);pos.push(l.x,l.y,l.z,r.x,r.y,r.z)}for(let i=0;i<segs;i++){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.84,metalness:.03,side:THREE.DoubleSide}));mesh.receiveShadow=true;world.add(mesh)}
buildRibbon(17.4,0xf4f1e9,.005);buildRibbon(16.6,0xd54246,.01);buildRibbon(15.5,0x303842,.02);
const grass=new THREE.Mesh(new THREE.PlaneGeometry(520,950),new THREE.MeshStandardMaterial({color:0x4e9a54,roughness:1}));grass.rotation.x=-Math.PI/2;grass.position.set(0,-.22,-385);grass.receiveShadow=true;world.add(grass);
function addBarrier(side){const mat=new THREE.MeshStandardMaterial({color:0x1682d6,roughness:.52,metalness:.12});for(let i=0;i<180;i++){const b=basisAt(i/179),m=new THREE.Mesh(new THREE.BoxGeometry(1.35,.7,.42),mat),p=b.p.clone().addScaledVector(b.right,side*9.1).addScaledVector(b.normal,.34);m.position.copy(p);m.lookAt(p.clone().add(b.tangent));m.castShadow=true;world.add(m)}}addBarrier(-1);addBarrier(1);
function addTree(t,side,scale=1){const b=basisAt(t),g=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22,.32,2.5,8),new THREE.MeshStandardMaterial({color:0x70503a,roughness:1}));trunk.position.y=1.25;g.add(trunk);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.7,1),new THREE.MeshStandardMaterial({color:0x267b46,roughness:.95}));crown.position.y=3.1;crown.scale.set(1,1.35,1);g.add(crown);g.position.copy(b.p.clone().addScaledVector(b.right,side*(10+Math.random()*10)));g.scale.setScalar(scale);world.add(g)}for(let i=0;i<145;i++)addTree((i+2)/150,i%2?1:-1,.55+Math.random()*.6);
function addGrandstand(t,side){const b=basisAt(t),g=new THREE.Group(),baseMat=new THREE.MeshStandardMaterial({color:0xd8dde4,roughness:.62}),roofMat=new THREE.MeshStandardMaterial({color:0x136dba,roughness:.4,metalness:.1});for(let k=0;k<4;k++){const row=new THREE.Mesh(new THREE.BoxGeometry(9,.45,2.2),baseMat);row.position.set(0,.45+k*.45,k*.75);g.add(row)}const roof=new THREE.Mesh(new THREE.BoxGeometry(10,.28,4),roofMat);roof.position.set(0,3.2,1.4);g.add(roof);g.position.copy(b.p.clone().addScaledVector(b.right,side*20));g.rotation.y=Math.atan2(b.tangent.x,b.tangent.z)+(side<0?Math.PI:0);world.add(g)}[.12,.31,.56,.78].forEach((t,i)=>addGrandstand(t,i%2?1:-1));
function addArch(t){const b=basisAt(t),g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x1476bf,metalness:.18,roughness:.38}),left=new THREE.Mesh(new THREE.BoxGeometry(.9,7,.9),mat),right=left.clone(),top=new THREE.Mesh(new THREE.BoxGeometry(18,.9,.9),mat);left.position.set(-8.4,3.5,0);right.position.set(8.4,3.5,0);top.position.set(0,7,0);g.add(left,right,top);g.position.copy(b.p);g.rotation.y=Math.atan2(b.tangent.x,b.tangent.z);world.add(g)}[.18,.47,.73,.95].forEach(addArch);
const pickupMat=new THREE.MeshPhysicalMaterial({color:0x55dbff,emissive:0x178bb2,emissiveIntensity:2.6,roughness:.13,metalness:.15}),pickups=[];for(let i=0;i<14;i++){const t=.08+i*.061,b=basisAt(t),mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.9),pickupMat),lane=[-4.2,0,4.2][i%3];mesh.castShadow=true;mesh.position.copy(b.p).addScaledVector(b.right,lane).addScaledVector(b.normal,1.1);world.add(mesh);pickups.push({mesh,t,lane,taken:false})}
const particleGeo=new THREE.SphereGeometry(.09,6,4),particles=[];function burst(pos,color,count=22,spread=5){const mat=new THREE.MeshBasicMaterial({color,transparent:true});for(let i=0;i<count;i++){const m=new THREE.Mesh(particleGeo,mat);m.position.copy(pos);world.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*spread,Math.random()*3,(Math.random()-.5)*spread),life:.7+Math.random()*.5})}}
const speedFx=new THREE.Group();camera.add(speedFx);scene.add(camera);const streakMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.22,depthTest:false}),streaks=[];for(let i=0;i<72;i++){const s=new THREE.Mesh(new THREE.BoxGeometry(.014,.014,3.2+Math.random()*4.8),streakMat);s.position.set((Math.random()-.5)*8,(Math.random()-.5)*4,-3-Math.random()*18);speedFx.add(s);streaks.push(s)}
let cars=[],player,ais=[];function prepModel(model){model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material)o.material.envMapIntensity=1.2}});const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());model.scale.setScalar(4.2/Math.max(size.x,size.z));const box2=new THREE.Box3().setFromObject(model);model.position.y-=box2.min.y;return model}
async function loadCars(){const models=await Promise.all(CAR_URLS.map(loadGLB));cars=models.map(prepModel);player=cars[0];world.add(player);ais=cars.slice(1).map((mesh,i)=>({mesh,t:.015+i*.009,lane:[-4,3,-1.5,4,-3][i],pace:.047+Math.random()*.005,stun:0,spin:0,speedScale:1,phase:i*1.7}));ais.forEach(a=>world.add(a.mesh))}
let running=false,targetLane=0,lane=0,playerT=0,boost=0,currentItem=null,last=performance.now(),dragging=false,dragX=0,dragLane=0,missiles=[],mines=[],shake=0,raceTime=0,throttle=0,accelerating=false,braking=false,leftHeld=false,rightHeld=false;
function showMsg(s){msgEl.textContent=s;msgEl.classList.add('show');clearTimeout(showMsg.t);showMsg.t=setTimeout(()=>msgEl.classList.remove('show'),800)}function setItem(v){currentItem=v;itemBtn.disabled=!v||!running;itemBtn.textContent=v==='rocket'?'🚀':v==='boost'?'⚡':v==='mine'?'💣':'?'}
function placeCar(mesh,t,laneValue){const b=basisAt(t),p=b.p.clone().addScaledVector(b.right,laneValue).addScaledVector(b.normal,.12);mesh.position.copy(p);mesh.rotation.y=Math.atan2(b.tangent.x,b.tangent.z);mesh.rotation.z=-Math.asin(THREE.MathUtils.clamp(b.tangent.y,-1,1))*.4}
function reset(){playerT=0;lane=targetLane=0;boost=0;raceTime=0;throttle=0;accelerating=false;braking=false;leftHeld=false;rightHeld=false;shake=0;setItem(null);pickups.forEach(p=>{p.taken=false;p.mesh.visible=true});ais.forEach((a,i)=>{a.t=.015+i*.009;a.stun=0;a.spin=0;a.speedScale=1});missiles.forEach(x=>world.remove(x.mesh));missiles=[];mines.forEach(x=>world.remove(x.mesh));mines=[];running=true;menu.style.display='none';showMsg('HOLD TO ACCELERATE')}
function useItem(){if(!running||!currentItem)return;const item=currentItem;setItem(null);if(item==='boost'){boost=1.7;showMsg('TURBO!');burst(player.position,0x55dfff,30,6)}else if(item==='mine'){const b=basisAt(playerT),m=new THREE.Mesh(new THREE.CylinderGeometry(.62,.62,.22,18),new THREE.MeshStandardMaterial({color:0xe44343,emissive:0x5f0909,emissiveIntensity:1.5}));m.position.copy(b.p).addScaledVector(b.right,lane).addScaledVector(b.normal,.18);world.add(m);mines.push({mesh:m,t:playerT,lane,life:14});showMsg('MINE DROPPED')}else{const target=ais.filter(a=>a.t>playerT).sort((a,b)=>a.t-b.t)[0];if(!target){showMsg('NO TARGET');return}const m=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.62,4,8),new THREE.MeshStandardMaterial({color:0xffcc3d,emissive:0xff5a00,emissiveIntensity:3.8}));m.rotation.x=Math.PI/2;m.position.copy(player.position);world.add(m);missiles.push({mesh:m,target,life:3});showMsg('ROCKET!')}}
itemBtn.addEventListener('click',useItem);playBtn.addEventListener('click',reset);
renderer.domElement.addEventListener('pointerdown',e=>{if(!running)return;dragging=true;accelerating=true;braking=false;dragX=e.clientX;dragLane=targetLane;renderer.domElement.setPointerCapture?.(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;targetLane=THREE.MathUtils.clamp(dragLane+(e.clientX-dragX)/Math.max(innerWidth,300)*16,-5.2,5.2)});
const endPointer=()=>{dragging=false;accelerating=false};renderer.domElement.addEventListener('pointerup',endPointer);renderer.domElement.addEventListener('pointercancel',endPointer);
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)||['KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();if(e.code==='ArrowUp'||e.code==='KeyW')accelerating=true;if(e.code==='ArrowDown'||e.code==='KeyS')braking=true;if(e.code==='ArrowLeft'||e.code==='KeyA')leftHeld=true;if(e.code==='ArrowRight'||e.code==='KeyD')rightHeld=true;if(e.code==='Space'&&!e.repeat)useItem()},{passive:false});
window.addEventListener('keyup',e=>{if(e.code==='ArrowUp'||e.code==='KeyW')accelerating=false;if(e.code==='ArrowDown'||e.code==='KeyS')braking=false;if(e.code==='ArrowLeft'||e.code==='KeyA')leftHeld=false;if(e.code==='ArrowRight'||e.code==='KeyD')rightHeld=false});
window.addEventListener('blur',()=>{accelerating=false;braking=false;leftHeld=false;rightHeld=false;dragging=false});
function update(dt){raceTime+=dt;if(leftHeld)targetLane=Math.max(-5.2,targetLane-dt*7.2);if(rightHeld)targetLane=Math.min(5.2,targetLane+dt*7.2);if(accelerating)throttle=Math.min(1,throttle+dt/5);else if(braking)throttle=Math.max(0,throttle-dt*.48);else throttle=Math.max(0,throttle-dt*.12);const launch=throttle*throttle*(3-2*throttle),aiRaw=THREE.MathUtils.clamp(raceTime/5,0,1),aiLaunch=aiRaw*aiRaw*(3-2*aiRaw),speedMul=boost>0?1.22:1;if(boost>0)boost-=dt;const playerPace=THREE.MathUtils.lerp(.004,.055,launch)*speedMul;playerT=Math.min(1,playerT+dt*playerPace);lane+=(targetLane-lane)*Math.min(1,dt*16);placeCar(player,playerT,lane);const turnAmount=THREE.MathUtils.clamp((targetLane-lane)*2.1,-1,1),trackRoll=-Math.asin(THREE.MathUtils.clamp(basisAt(playerT).tangent.y,-1,1))*.4;player.rotation.z+=(trackRoll-turnAmount*.18-player.rotation.z)*Math.min(1,dt*13);
ais.forEach(a=>{if(a.speedScale<1)a.speedScale=Math.min(1,a.speedScale+dt*.4);const impact=a.stun>0?.72:1,aiPace=THREE.MathUtils.lerp(a.pace*.38,a.pace,aiLaunch);a.t=Math.min(1,a.t+dt*aiPace*a.speedScale*impact);if(a.stun>0){a.stun-=dt;a.spin+=dt*10}const aiLane=a.lane+Math.sin(a.t*80+a.phase)*1.05;placeCar(a.mesh,a.t,aiLane);if(a.stun>0)a.mesh.rotation.y+=a.spin});
pickups.forEach(p=>{p.mesh.rotation.x+=dt*2.5;p.mesh.rotation.y+=dt*3.5;if(!p.taken&&Math.abs(p.t-playerT)<.018&&Math.abs(p.lane-lane)<1.8){p.taken=true;p.mesh.visible=false;if(!currentItem){const r=Math.random();setItem(r<.47?'rocket':r<.75?'boost':'mine');showMsg('ITEM READY');burst(player.position,0x65e6ff,18,3)}}});
missiles.forEach(m=>{m.life-=dt;const tp=m.target.mesh.position;m.mesh.position.lerp(tp,.32);const dir=tp.clone().sub(m.mesh.position).normalize();m.mesh.position.addScaledVector(dir,dt*260);m.mesh.rotation.z+=dt*22;if(m.mesh.position.distanceTo(tp)<2.6){m.target.stun=1.2;m.target.speedScale=Math.min(m.target.speedScale,.18);m.life=0;shake=.55;showMsg('DIRECT HIT!');burst(tp,0xffb532,34,7)}});for(let i=missiles.length-1;i>=0;i--)if(missiles[i].life<=0){world.remove(missiles[i].mesh);missiles.splice(i,1)}
mines.forEach(m=>{m.life-=dt;ais.forEach(a=>{if(m.life>0&&Math.abs(a.t-m.t)<.018&&Math.abs(a.lane-m.lane)<2){a.stun=1.1;a.speedScale=Math.min(a.speedScale,.28);m.life=0;burst(m.mesh.position,0xff5a44,28,6)}})});for(let i=mines.length-1;i>=0;i--)if(mines[i].life<=0){world.remove(mines[i].mesh);mines.splice(i,1)}
particles.forEach(p=>{p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=4.8*dt;p.m.material.opacity=Math.max(0,p.life/.8)});for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0){world.remove(particles[i].m);particles.splice(i,1)}
const visualSpeed=THREE.MathUtils.lerp(0,345,launch)*speedMul;speedEl.textContent=Math.round(visualSpeed);rankEl.textContent=[playerT,...ais.map(a=>a.t)].sort((a,b)=>b-a).indexOf(playerT)+1;progressEl.style.width=(playerT*100).toFixed(1)+'%';const b=basisAt(playerT),cameraDistance=THREE.MathUtils.lerp(5.7,7.0,launch),cameraHeight=THREE.MathUtils.lerp(2.0,2.5,launch),behind=b.p.clone().addScaledVector(b.tangent,-cameraDistance).addScaledVector(b.normal,cameraHeight).addScaledVector(b.right,lane*.085),roadBuzz=.06*launch+(boost>0?.06:0);behind.x+=(Math.random()-.5)*roadBuzz;behind.y+=(Math.random()-.5)*roadBuzz;if(shake>0){behind.x+=(Math.random()-.5)*shake;behind.y+=(Math.random()-.5)*shake;shake=Math.max(0,shake-dt*1.9)}camera.position.lerp(behind,1-Math.pow(.000012,dt));camera.lookAt(b.p.clone().addScaledVector(b.tangent,THREE.MathUtils.lerp(24,38,launch)).addScaledVector(b.normal,.55));const targetFov=THREE.MathUtils.lerp(82,96,launch)+(boost>0?8:0);camera.fov+=(targetFov-camera.fov)*dt*10;camera.updateProjectionMatrix();streakMat.opacity=.03+.33*launch+(boost>0?.16:0);streaks.forEach(s=>{s.position.z+=dt*(20+visualSpeed*.22);if(s.position.z>-1){s.position.z=-20-Math.random()*10;s.position.x=(Math.random()-.5)*8;s.position.y=(Math.random()-.5)*4}});if(playerT>=1){running=false;accelerating=false;braking=false;leftHeld=false;rightHeld=false;setItem(null);const final=[playerT,...ais.map(a=>a.t)].sort((a,b)=>b-a).indexOf(playerT)+1;document.querySelector('.title').innerHTML=final===1?'VICTORY!':'FINISHED '+final+'/6';document.querySelector('.subtitle').textContent=final===1?'First place. Smart item timing and clean lines won the race.':'Use pickups more aggressively and save turbo for overtakes.';playBtn.textContent='RACE AGAIN';menu.style.display='flex'}}
function animate(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(running)update(dt);else if(player){player.rotation.y+=dt*.1;streakMat.opacity=.02}renderer.render(scene,camera);requestAnimationFrame(animate)}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
(async()=>{try{loadingEl.textContent='Loading polished car models…';await loadCars();placeCar(player,0,0);ais.forEach(a=>placeCar(a.mesh,a.t,a.lane));const b=basisAt(0);camera.position.copy(b.p).addScaledVector(b.tangent,-5.7).addScaledVector(b.normal,2.0);camera.lookAt(b.p.clone().addScaledVector(b.tangent,24));playBtn.disabled=false;playBtn.textContent='START RACE';loadingEl.textContent='Ready'}catch(err){console.error(err);loadingEl.textContent='Could not load remote CC0 car assets. Check internet access.';playBtn.textContent='ASSET LOAD FAILED'}})();
requestAnimationFrame(animate);